export const QM_TYPES = {
	QUIZ_REPOSITORY: Symbol('QM_QUIZ_REPOSITORY'),
	QUIZ_EXECUTION_REPOSITORY: Symbol('QM_QUIZ_EXECUTION_REPOSITORY'),
	QUESTION_REPOSITORY: Symbol('QM_QUESTION_REPOSITORY'),
	QUIZ_SERVICE: Symbol('QM_QUIZ_SERVICE'),
	QUESTION_SERVICE: Symbol('QM_QUESTION_SERVICE'),
	QUIZ_CONTROLLER: Symbol('QM_QUIZ_CONTROLLER'),
	QUESTION_CONTROLLER: Symbol('QM_QUESTION_CONTROLLER'),
	QUIZ_MIDDLEWARE: Symbol('QM_QUIZ_MIDDLEWARE'),
	QUIZ_OWNERSHIP_GUARD: Symbol('QM_QUIZ_OWNERSHIP_GUARD'),
} as const;
