export const QM_TYPES = {
	QUIZ_REPOSITORY: Symbol('QM_QUIZ_REPOSITORY'),
	CREATE_QUIZ_HANDLER: Symbol('QM_CREATE_QUIZ_HANDLER'),
	UPDATE_QUIZ_HANDLER: Symbol('QM_UPDATE_QUIZ_HANDLER'),
	UPDATE_QUIZ_SETTINGS_HANDLER: Symbol('QM_UPDATE_QUIZ_SETTINGS_HANDLER'),
	DELETE_QUIZ_HANDLER: Symbol('QM_DELETE_QUIZ_HANDLER'),
	GET_QUIZ_BY_ID_HANDLER: Symbol('QM_GET_QUIZ_BY_ID_HANDLER'),
	GET_QUIZZES_BY_AUTHOR_HANDLER: Symbol('QM_GET_QUIZZES_BY_AUTHOR_HANDLER'),
	QUIZ_CONTROLLER: Symbol('QM_QUIZ_CONTROLLER'),
} as const;
