import { SHARED_TYPES } from '@shared/di/types';

export const APP_TYPES = {
	APP: Symbol('APP'),
	PRISMA: Symbol('PRISMA'),
	LOGGER: SHARED_TYPES.LOGGER,
	CONFIG: SHARED_TYPES.CONFIG,
	HASH_SERVICE: Symbol('HASH_SERVICE'),
	MIDDLEWARE_FACTORY: Symbol('MIDDLEWARE_FACTORY'),
	REQUEST_CONTEXT_MIDDLEWARE: Symbol('REQUEST_CONTEXT_MIDDLEWARE'),
	REQUEST_LOGGER_MIDDLEWARE: Symbol('REQUEST_LOGGER_MIDDLEWARE'),
	EXCEPTION_FILTER: SHARED_TYPES.EXCEPTION_FILTER,
	SWAGGER: Symbol('SWAGGER'),
};
