export const AUTH_TYPES = {
	AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),
	AUTH_MIDDLEWARE: Symbol('AUTH_MIDDLEWARE'),
	AUTH_GUARD: Symbol('AUTH_GUARD'),
	AUTH_SERVICE: Symbol('AUTH_SERVICE'),
	TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
	REFRESH_TOKEN_COOKIE_SERVICE: Symbol('REFRESH_TOKEN_COOKIE_SERVICE'),
};
