import { ContainerModule, type ContainerModuleLoadOptions } from 'inversify';
import { QUIZ_TYPES } from './quiz.types';
import { QuestionRepository } from '@infrastructure/persistence/prisma/question.repository';
import { PrismaQuizRepository } from '@infrastructure/persistence/prisma/quiz.repository';
import { QuizService } from '@application/quiz/quiz.service';
import { QuizController } from '@interfaces/http/quiz/quiz.controller';
import type { QuizRepository } from '@domain/quiz/ports/quiz.repository.port';
import type { IQuestionRepository } from '@infrastructure/persistence/prisma/question.repository.interface';
import type { IQuizService } from '@application/quiz/quiz.service.interface';
import type { IController } from '@common/controller.interface';
import { type IQuestionService } from '@application/quiz/question.service.interface';
import { QuestionService } from '@application/quiz/question.service';
import { QuizOwnershipPolicy } from '@domain/quiz/policies/quiz-ownership.policy';
import type { IQuizOwnershipPolicy } from '@domain/quiz/policies/quiz-ownership.policy.interface';
import { QuizQueryService } from '@application/quiz/quiz-query.service';
import type { IQuizQueryService } from '@application/quiz/quiz-query.service.interface';
import { QuizPersistenceMapper } from '@infrastructure/persistence/mappers/quiz-persistence.mapper';
import { QuizMapper } from '@infrastructure/persistence/mappers/quiz.mapper';
import { QuestionMapper } from '@infrastructure/persistence/mappers/question.mapper';
import { QuestionConfigFactory } from '@domain/quiz/question-configs/question-config.factory';
import type { IQuestionConfigFactory } from '@domain/quiz/question-configs/question-config.factory';
import { AnswerEvaluationService } from '@application/quiz/execution/answer-evaluation.service';
import type { IAnswerEvaluationService } from '@application/quiz/execution/answer-evaluation.service.interface';
import { QuizExecuteController } from '@interfaces/http/quiz/quiz-execute.controller';

const quizContainer: ContainerModule = new ContainerModule((options: ContainerModuleLoadOptions) => {
	options.bind<IQuestionConfigFactory>(QUIZ_TYPES.QUESTION_CONFIG_FACTORY).to(QuestionConfigFactory).inSingletonScope();
	options.bind<QuestionMapper>(QUIZ_TYPES.QUESTION_MAPPER).to(QuestionMapper).inSingletonScope();
	options.bind<QuizMapper>(QUIZ_TYPES.QUIZ_MAPPER).to(QuizMapper).inSingletonScope();
	options.bind<QuizPersistenceMapper>(QUIZ_TYPES.QUIZ_PERSISTENCE_MAPPER).to(QuizPersistenceMapper).inSingletonScope();
	options.bind<IQuestionRepository>(QUIZ_TYPES.QUESTION_REPOSITORY).to(QuestionRepository).inSingletonScope();
	options.bind<QuizRepository>(QUIZ_TYPES.QUIZ_REPOSITORY).to(PrismaQuizRepository).inSingletonScope();
	options.bind<IQuizQueryService>(QUIZ_TYPES.QUIZ_QUERY_SERVICE).to(QuizQueryService).inSingletonScope();
	options.bind<IQuizService>(QUIZ_TYPES.QUIZ_SERVICE).to(QuizService).inSingletonScope();
	options.bind<IController>(QUIZ_TYPES.QUIZ_CONTROLLER).to(QuizController).inSingletonScope();
	options.bind<IQuestionService>(QUIZ_TYPES.QUESTION_SERVICE).to(QuestionService).inSingletonScope();
	options.bind<IQuizOwnershipPolicy>(QUIZ_TYPES.QUIZ_OWNERSHIP_POLICY).to(QuizOwnershipPolicy).inSingletonScope();
	options.bind<IAnswerEvaluationService>(QUIZ_TYPES.ANSWER_EVALUATION_SERVICE).to(AnswerEvaluationService).inSingletonScope();
	options.bind<IController>(QUIZ_TYPES.QUIZ_EXECUTE_CONTROLLER).to(QuizExecuteController).inSingletonScope();
});

export { quizContainer, QUIZ_TYPES, type IQuestionRepository, type QuizRepository, type IQuizService, type IQuestionService };
