export const QUIZ_TYPES = {
	QUIZ_REPOSITORY: Symbol('QUIZ_REPOSITORY'),
	QUESTION_REPOSITORY: Symbol('QUESTION_REPOSITORY'),
	QUIZ_SERVICE: Symbol('QUIZ_SERVICE'),
	QUIZ_CONTROLLER: Symbol('QUIZ_CONTROLLER'),
	QUESTION_SERVICE: Symbol('QUESTION_SERVICE'),

	QUIZ_OWNERSHIP_POLICY: Symbol('QUIZ_OWNERSHIP_POLICY'),
	QUIZ_QUERY_SERVICE: Symbol('QUIZ_QUERY_SERVICE'),
	QUIZ_MAPPER: Symbol('QUIZ_MAPPER'),
	QUESTION_MAPPER: Symbol('QUESTION_MAPPER'),
	QUESTION_CONFIG_FACTORY: Symbol('QUESTION_CONFIG_FACTORY'),
	QUIZ_PERSISTENCE_MAPPER: Symbol('QUIZ_PERSISTENCE_MAPPER'),
	ANSWER_EVALUATION_SERVICE: Symbol('ANSWER_EVALUATION_SERVICE'),
	QUIZ_EXECUTE_CONTROLLER: Symbol('QUIZ_EXECUTE_CONTROLLER'),
};
