export const TE_TYPES = {
	QUESTION_READ_REPOSITORY: Symbol('QE_QUESTION_READ_REPOSITORY'),
	TEST_EXECUTION_SERVICE: Symbol('QE_TEST_EXECUTION_SERVICE'),
	TEST_SESSION_SERVICE: Symbol('QE_TEST_SESSION_SERVICE'),
	TEST_EXECUTE_CONTROLLER: Symbol('QE_TEST_EXECUTE_CONTROLLER'),
} as const;
