export const TE_TYPES = {
	QUESTION_READ_REPOSITORY: Symbol('QE_QUESTION_READ_REPOSITORY'),
	TEST_EXECUTION_SERVICE: Symbol('QE_TEST_EXECUTION_SERVICE'),
	TEST_EXECUTE_CONTROLLER: Symbol('QE_TEST_EXECUTE_CONTROLLER'),
	TEST_REGISTER_REPOSITORY: Symbol('QE_TEST_REGISTER_REPOSITORY'),
	ANSWER_REPOSITORY: Symbol('QE_ANSWER_REPOSITORY'),
} as const;
