export const QE_TYPES = {
	QUESTION_READ_REPOSITORY: Symbol('QE_QUESTION_READ_REPOSITORY'),
	QUIZ_EXECUTION_REPOSITORY: Symbol('QE_QUIZ_EXECUTION_REPOSITORY'),
	EVALUATE_ANSWER_HANDLER: Symbol('QE_EVALUATE_ANSWER_HANDLER'),
	START_QUIZ_HANDLER: Symbol('QE_START_QUIZ_HANDLER'),
	FINISH_QUIZ_HANDLER: Symbol('QE_FINISH_QUIZ_HANDLER'),
	GET_QUIZ_FOR_EXECUTION_HANDLER: Symbol('QE_GET_QUIZ_FOR_EXECUTION_HANDLER'),
	GET_QUESTION_FOR_EXECUTION_HANDLER: Symbol('QE_GET_QUESTION_FOR_EXECUTION_HANDLER'),
	QUIZ_EXECUTE_CONTROLLER: Symbol('QE_QUIZ_EXECUTE_CONTROLLER'),
} as const;
