export const QE_TYPES = {
	QUESTION_READ_REPOSITORY: Symbol('QE_QUESTION_READ_REPOSITORY'),
	QUIZ_EXECUTION_SERVICE: Symbol('QE_QUIZ_EXECUTION_SERVICE'),
	QUIZ_SESSION_SERVICE: Symbol('QE_QUIZ_SESSION_SERVICE'),
	QUIZ_EXECUTE_CONTROLLER: Symbol('QE_QUIZ_EXECUTE_CONTROLLER'),
} as const;
