export const QM_TYPES = {
	QUESTION_REPOSITORY: Symbol('QM_QUESTION_REPOSITORY'),
	QUESTION_SERVICE: Symbol('QM_QUESTION_SERVICE'),
	QUESTION_CONTROLLER: Symbol('QM_QUESTION_CONTROLLER'),
} as const;
