export const AUTH_TYPES = {
	AUTH_CONTROLLER: Symbol('AUTH_CONTROLLER'),
	AUTH_MIDDLEWARE: Symbol('AUTH_MIDDLEWARE'),
	AUTH_SERVICE: Symbol('AUTH_SERVICE'),
	TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
};
