export const APP_TYPES = {
	APP: Symbol('APP'),
	LOGGER: Symbol('LOGGER'),
	PRISMA: Symbol('PRISMA'),
	CONFIG: Symbol('CONFIG'),
	HASH_SERVICE: Symbol('HASH_SERVICE'),
	MIDDLEWARE_FACTORY: Symbol('MIDDLEWARE_FACTORY'),
	REQUEST_CONTEXT_MIDDLEWARE: Symbol('REQUEST_CONTEXT_MIDDLEWARE'),
	REQUEST_LOGGER_MIDDLEWARE: Symbol('REQUEST_LOGGER_MIDDLEWARE'),
	EXCEPTION_FILTER: Symbol('EXCEPTION_FILTER'),
	SWAGGER: Symbol('SWAGGER'),
};
