export { testManagementModule, TM_TYPES } from './test-management.module';
export { TestId } from './entities/value-object/test-id';
export { QuestionId } from './entities/value-object/question-id';
export { TestEntity } from './entities/test.entity';
export { QuestionEntity } from './entities/question.entity';
export type { TestRepository } from './interfaces/repository/test.repository.interface';
export type { QuestionRepository } from './interfaces/repository/question.repository.interface';
export type { TestExecutionRepository } from './interfaces/repository/test-execution.repository.interface';
export { TestNotFoundError } from './utils/errors/test-not-found.error';
export { TestNotOwnedError } from './utils/errors/test-not-owned.error';
export { TestValidationFailedError } from './utils/errors/test-validation-failed.error';
export { UnknownQuestionTypeError } from './utils/errors/unknown-question-type.error';
export { createQuestionConfigFromPayload, isQuestionType, QUESTION_TYPES } from './entities/question-configs/question-config.registry';
export type { QuestionConfigBase } from './entities/question-configs/question-config.base';
export type { QuestionType } from './entities/question-configs/question-type';
export type { QuestionConfigSingleChoise } from './entities/question-configs/question-config-single-choise';
export type { QuestionConfigMultipleChoise } from './entities/question-configs/question-config-multiple-choise';
export type { QuestionConfigInputValue } from './entities/question-configs/question-config-input-value';
export type { IQuestionConfigOrderValuesAnswer, QuestionConfigOrderValues } from './entities/question-configs/question-config-order-values';
