import { ContainerModule, type ContainerModuleLoadOptions } from 'inversify';
import { TM_TYPES } from './test-management.types';
import type { QuestionRepository } from './interfaces/repository/question.repository.interface';
import { PrismaQuestionRepository } from './repositories/prisma-question.repository';
import { DefaultTestService } from './services/test.service';
import { DefaultQuestionService } from './services/question.service';
import { TestController } from './controllers/test.controller';
import { QuestionController } from './controllers/question.controller';
import { TestMiddleware } from './middlewares/test.middleware';
import { TestOwnershipGuard } from './middlewares/test-ownership.guard';
import type { TestRepository } from './interfaces/repository/test.repository.interface';
import { PrismaTestRepository } from './repositories/prisma-test.repository';
import { DefaultTestSessionService } from './services/test-session.service';
import { QuestionExistsGuard } from './middlewares/question-exists.guard';
import type { TestSessionRepository } from './interfaces/repository/test-session.repository.interface';
import { PrismaTestSessionRepository } from './repositories/prisma-test-session.repository';
import type { TestSettingsRepository } from './interfaces/repository/test-settings.repository.interface';
import { PrismaTestSettingsRepository } from './repositories/prisma-test-settings.repository';
import type { TestSchedulerRepository } from './interfaces/repository/test-scheduler.repository.interface';
import { PrismaTestSchedulerRepository } from './repositories/prisma-test-scheduler.repository';
import { DefaultTestOverviewService } from './services/test-overview.service';

const testManagementModule: ContainerModule = new ContainerModule((options: ContainerModuleLoadOptions) => {
	options.bind<TestRepository>(TM_TYPES.TEST_REPOSITORY).to(PrismaTestRepository).inSingletonScope();
	options.bind<TestSessionRepository>(TM_TYPES.TEST_SESSION_REPOSITORY).to(PrismaTestSessionRepository).inSingletonScope();
	options.bind<QuestionRepository>(TM_TYPES.QUESTION_REPOSITORY).to(PrismaQuestionRepository).inSingletonScope();
	options.bind<TestSettingsRepository>(TM_TYPES.TEST_SETTINGS_REPOSITORY).to(PrismaTestSettingsRepository).inSingletonScope();
	options.bind<TestSchedulerRepository>(TM_TYPES.TEST_SCHEDULER_REPOSITORY).to(PrismaTestSchedulerRepository).inSingletonScope();
	options.bind(TM_TYPES.TEST_SERVICE).to(DefaultTestService).inSingletonScope();
	options.bind(TM_TYPES.QUESTION_SERVICE).to(DefaultQuestionService).inSingletonScope();
	options.bind(TM_TYPES.TEST_CONTROLLER).to(TestController).inSingletonScope();
	options.bind(TM_TYPES.QUESTION_CONTROLLER).to(QuestionController).inSingletonScope();
	options.bind(TM_TYPES.TEST_MIDDLEWARE).to(TestMiddleware).inSingletonScope();
	options.bind(TM_TYPES.TEST_OWNERSHIP_GUARD).to(TestOwnershipGuard).inSingletonScope();
	options.bind(TM_TYPES.TEST_SESSION_SERVICE).to(DefaultTestSessionService).inSingletonScope();
	options.bind(TM_TYPES.QUESTION_EXISTS_GUARD).to(QuestionExistsGuard).inSingletonScope();
	options.bind(TM_TYPES.TEST_OVERVIEW_SERVICE).to(DefaultTestOverviewService).inSingletonScope();
});

export { testManagementModule, TM_TYPES };
