export const TM_TYPES = {
	TEST_REPOSITORY: Symbol('QM_TEST_REPOSITORY'),
	TEST_EXECUTION_REPOSITORY: Symbol('QM_TEST_EXECUTION_REPOSITORY'),
	QUESTION_REPOSITORY: Symbol('QM_QUESTION_REPOSITORY'),
	TEST_SERVICE: Symbol('QM_TEST_SERVICE'),
	QUESTION_SERVICE: Symbol('QM_QUESTION_SERVICE'),
	TEST_CONTROLLER: Symbol('QM_TEST_CONTROLLER'),
	QUESTION_CONTROLLER: Symbol('QM_QUESTION_CONTROLLER'),
	TEST_MIDDLEWARE: Symbol('QM_TEST_MIDDLEWARE'),
	TEST_OWNERSHIP_GUARD: Symbol('QM_TEST_OWNERSHIP_GUARD'),
	TEST_SESSION_SERVICE: Symbol('QM_TEST_SESSION_SERVICE'),
} as const;
