export const QUIZ_TYPES = {
	QUIZ_REPOSITORY: Symbol('QUIZ_REPOSITORY'),
	QUESTION_REPOSITORY: Symbol('QUESTION_REPOSITORY'),
	QUIZ_SERVICE: Symbol('QUIZ_SERVICE'),
	QUIZ_CONTROLLER: Symbol('QUIZ_CONTROLLER'),
	QUESTION_SERVICE: Symbol('QUESTION_SERVICE'),
};
